#!/usr/bin/env python3
"""Build the self-contained offline/PWA HTML used by Electron and static hosts."""
from __future__ import annotations

import hashlib
import json
import math
import shutil
from pathlib import Path

from build_desktop_inline import write_offline_html

ROOT = Path(__file__).resolve().parent.parent
DIST_INDEX = ROOT / "dist" / "index.html"


def remove_legacy_vendor_assets() -> None:
    """Discard sidecars from older offline builds; this build embeds them."""
    dist = DIST_INDEX.parent
    stale = dist / "vendor"
    if not stale.exists() and not stale.is_symlink():
        return
    resolved_root = ROOT.resolve()
    resolved_dist = dist.resolve()
    resolved_stale = stale.resolve()
    if not resolved_dist.is_relative_to(resolved_root) or not resolved_stale.is_relative_to(resolved_dist):
        raise SystemExit(f"ERROR: refusing to remove vendor path outside project dist: {stale}")
    if stale.is_symlink():
        stale.unlink()
    elif stale.is_dir():
        shutil.rmtree(stale)
    else:
        stale.unlink()
    print("  removed obsolete dist/vendor sidecars")

# The service worker cache name is derived from the built bytes below. A new
# build must not depend on someone remembering to bump a manual version.
PWA_CACHE_PREFIX = "e8-studio-"

# Core assets the service worker precaches so the app loads with no network.
PWA_PRECACHE = ["./", "./index.html", "./manifest.webmanifest", "./icon.svg"]


def pwa_cache_name(dist_dir: Path, precache: list[str] = PWA_PRECACHE) -> str:
    """Identify this build by the assets that can be served from the cache."""
    digest = hashlib.sha256()
    names = [asset.removeprefix("./") for asset in precache if asset != "./"]
    names.extend(name for name in ("icon-192.png", "icon-512.png") if (dist_dir / name).is_file())
    for name in names:
        path = dist_dir / name
        if not path.is_file():
            raise SystemExit(f"ERROR: missing PWA precache asset: {path}")
        digest.update(name.encode("utf-8") + b"\0")
        digest.update(path.read_bytes() + b"\0")
    return PWA_CACHE_PREFIX + digest.hexdigest()[:16]

PWA_MANIFEST = {
    "name": "E8 ⇄ Platonics Studio",
    "short_name": "E8 Studio",
    "description": "Interactive E8 root system and Platonic-solid visualization.",
    "start_url": "./",
    "scope": "./",
    "display": "standalone",
    "orientation": "any",
    "background_color": "#07070c",
    "theme_color": "#07070c",
    "icons": [
        {"src": "./icon.svg", "sizes": "any", "type": "image/svg+xml", "purpose": "any"},
        {"src": "./icon.svg", "sizes": "any", "type": "image/svg+xml", "purpose": "maskable"},
        # Raster fallbacks (optional) — produced by scripts/gen_pwa_icons.py.
        {"src": "./icon-192.png", "sizes": "192x192", "type": "image/png"},
        {"src": "./icon-512.png", "sizes": "512x512", "type": "image/png"},
    ],
}

def _pwa_icon_svg() -> str:
    """A self-contained icon with a decorative 12-dot ring."""
    dots = "".join(
        f'    <circle cx="{256 + 170 * math.cos(i * math.pi / 6):.1f}" '
        f'cy="{256 + 170 * math.sin(i * math.pi / 6):.1f}" r="11"/>\n'
        for i in range(12)
    )
    return (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">\n'
        '  <rect width="512" height="512" rx="96" fill="#07070c"/>\n'
        '  <g fill="none" stroke="#f0a04b" stroke-width="3" opacity="0.5">\n'
        '    <circle cx="256" cy="256" r="170"/>\n'
        '    <circle cx="256" cy="256" r="110"/>\n'
        '  </g>\n'
        f'  <g fill="#f4d27a">\n{dots}  </g>\n'
        '  <circle cx="256" cy="256" r="16" fill="#fff"/>\n'
        '</svg>\n'
    )


def write_pwa_assets(dist_dir: Path = DIST_INDEX.parent, precache: list[str] = PWA_PRECACHE) -> str:
    """Write the manifest, service worker, and icon the dist references.

    build_offline injects <link rel=manifest> + a SW registration into the dist
    HTML, but those files have to exist or the PWA silently no-ops (manifest +
    sw.js 404, no offline cache). This generates them so `npm run pwa` produces a
    genuinely installable, offline-capable build with no extra tooling.
    """
    dist_dir.mkdir(parents=True, exist_ok=True)
    (dist_dir / "manifest.webmanifest").write_text(
        json.dumps(PWA_MANIFEST, indent=2), encoding="utf-8")
    (dist_dir / "icon.svg").write_text(_pwa_icon_svg(), encoding="utf-8")

    cache_name = pwa_cache_name(dist_dir, precache)
    precache_json = json.dumps(precache)
    sw = f"""// sw.js — generated by scripts/build_offline.py for the offline E8 Studio PWA.
// HTML navigations check the network first; other cached assets work offline.
const CACHE_PREFIX = {PWA_CACHE_PREFIX!r};
const CACHE = {cache_name!r};
const PRECACHE = {precache_json};

self.addEventListener('install', (e) => {{
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
}});

self.addEventListener('activate', (e) => {{
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith(CACHE_PREFIX) && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
}});

self.addEventListener('fetch', (e) => {{
  const request = e.request;
  if (request.method !== 'GET') return;
  const sameOrigin = new URL(request.url).origin === self.location.origin;
  if (request.mode === 'navigate') {{
    e.respondWith(fetch(request).then(async (response) => {{
      if (sameOrigin && response.ok) {{
        try {{
          const cache = await caches.open(CACHE);
          await cache.put(request, response.clone());
        }} catch (error) {{
          console.warn('[pwa] Could not cache navigation:', error);
        }}
      }}
      return response;
    }}).catch(async () => {{
      const cache = await caches.open(CACHE);
      return (await cache.match(request)) || (await cache.match('./index.html')) || Response.error();
    }}));
    return;
  }}
  e.respondWith(caches.open(CACHE).then(async (cache) => {{
    const hit = await cache.match(request);
    if (hit) return hit;
    const response = await fetch(request);
    if (sameOrigin && response.ok) await cache.put(request, response.clone());
    return response;
  }}));
}});
"""
    (dist_dir / "sw.js").write_text(sw, encoding="utf-8", newline="\n")
    print(f"  wrote manifest.webmanifest, sw.js, icon.svg (cache {cache_name})")
    return cache_name


def main() -> int:
    print("Building Vite-backed offline/PWA/Electron HTML...")
    remove_legacy_vendor_assets()
    write_offline_html(DIST_INDEX)
    write_pwa_assets()
    print(f"Offline dist written: {DIST_INDEX.relative_to(ROOT)} ({DIST_INDEX.stat().st_size:,} bytes)")
    print("Runtime code, CSS, and data are inlined; no vendor files are needed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
