"""Shared fuzzer action definitions (importable without side effects)."""

# All actions the user can take via the panel
ACTIONS = [
    ('view', 'bloom'), ('view', 'platonic'), ('view', 'e8coxeter'),
    ('view', 'sixhundred'), ('view', 'polytope'), ('view', 'raymarched'),
    ('palette', 'gold'), ('palette', 'ember'), ('palette', 'rainbow'),
    ('palette', 'aurora'), ('palette', 'neon'), ('palette', 'fire'),
    ('fx', 'glow'), ('fx', 'pulse'), ('fx', 'trail'), ('fx', 'chromatic'),
    ('fx', 'kaleidoscope'), ('fx', 'ripple'), ('fx', 'spiral'), ('fx', 'fog'),
    ('fx', 'aura'), ('fx', 'voronoi'), ('fx', 'plasma'), ('fx', 'nebula'),
    ('fx', 'wireframe'), ('fx', 'kaleido6'), ('fx', 'dof'), ('fx', 'none'),
    # Previously-uncovered FX modes (added so the fuzzer exercises all 24).
    ('fx', 'heat'), ('fx', 'edge-glow'), ('fx', 'caustic'), ('fx', 'iridescent'),
    ('fx', 'flowfield'), ('fx', 'hologram'), ('fx', 'xray'), ('fx', 'crystal'),
    ('bg', 'void'), ('bg', 'starfield'), ('bg', 'milkyway'), ('bg', 'cosmos'),
    ('bg', 'aurora'), ('bg', 'mandala'), ('bg', 'grid'), ('bg', 'plasma'),
    ('theme', 'dark-gold'), ('theme', 'paper-ink'), ('theme', 'neon-cyber'),
    ('theme', 'pure-dark'), ('theme', 'solarized'),
    ('layout', 'default'), ('layout', 'compact'), ('layout', 'wide-canvas'),
    ('layout', 'presentation'),
    ('shape', 'tetrahedron'), ('shape', 'cube'), ('shape', 'octahedron'),
    ('shape', 'dodecahedron'), ('shape', 'icosahedron'),
    ('stack', 'single'), ('stack', 'dual'), ('stack', 'all5'), ('stack', 'nested'),
    ('blend', 'spectrum'), ('blend', 'sector'), ('blend', 'radial'),
    ('blend', 'mirror'), ('blend', 'random'),
    # E8-native colorings (the project's own color-by-structure control)
    ('colorBy', 'shell'), ('colorBy', 'radius'), ('colorBy', 'phase'),
    ('colorBy', 'axis'), ('colorBy', 'index'), ('colorBy', 'mono'),
    # Per-slider auto-animate toggles
    ('sliderAuto', 'fxIntensity'), ('sliderAuto', 'opacity'),
    ('sliderAuto', 'rotationSpeed'), ('sliderAuto', 'bgIntensity'),
    ('shift', 'static'), ('shift', 'sunset'), ('shift', 'rainbow'),
    ('shift', 'fire'), ('shift', 'cool'), ('shift', 'warm'),
    ('cam-mode', 'orbit'), ('cam-mode', 'spiral'), ('cam-mode', 'figure8'),
    ('cam-mode', 'pullback'),
    ('cam-path', 'manual'), ('cam-path', 'coxeterOrbit'),
    ('cam-path', 'ringDive'), ('cam-path', 'petrieSpiral'),
    ('toggle', 'autoRotate'), ('toggle', 'autoZoom'),
    ('toggle', 'rootDiffusion'), ('toggle', 'showPetrie'),
    ('toggle', 'showRings'), ('toggle', 'showEdges'),
    ('toggle', 'e8Twin600'), ('toggle', 'e8ProjectionAuto'),
    ('toggle', 'weylOrbit'), ('toggle', 'showWeylMirrors'),
    ('toggle', 'h4TwinReveal'), ('toggle', 'bloomMandelbox'),
    ('toggle', 'bloomAuto'), ('toggle', 'paused'),
    ('toggle', 'showInspector'), ('toggle', 'showPerf'),
    ('toggle', 'adaptivePixelRatio'),
    ('e8-mode', 'coxeter'), ('e8-mode', 'petrie'), ('e8-mode', 'h4'),
    ('e8-mode', 'ortho3d'), ('e8-mode', 'custom'),
    ('action', 'surprise'), ('action', 'resetCamera'),
    ('action', 'resetE8Angles'), ('action', 'resetPolyAngles'),
    ('action', 'sharePage'), ('action', 'shareSnapshot'), ('action', 'toggleTour'),
    ('action', 'togglePerf'), ('action', 'toggleCommandPalette'),
    ('slider', 'fxIntensity', 0.0, 1.0),
    ('slider', 'bgIntensity', 0.0, 1.5),
    ('slider', 'shiftSpeed', 1, 120),
    ('slider', 'rotationSpeed', 0.0, 0.02),
    ('slider', 'opacity', 0.1, 1.0),
    ('slider', 'bloomAmount', 0, 1),
    ('slider', 'morph4d', -2, 2),
    ('slider', 'e8MorphT', 0, 1),
    ('slider', 'e8Spin', -3.14, 3.14),
    ('slider', 'e8Tilt', -3.14, 3.14),
    ('slider', 'e8Roll', -3.14, 3.14),
    ('slider', 'bloomMandelboxScale', 1.5, 3.5),
    ('slider', 'bloomMandelboxIters', 1, 12),
    ('slider', 'bloomMandelboxMix', 0, 1),
    ('slider', 'sdfSphereR', 0.02, 0.15),
    ('slider', 'sdfBlend', 0, 0.12),
    ('slider', 'sdfBloom', 0, 1),
    ('slider', 'sdfAniso', 0, 1),
    ('slider', 'sdfEdges', 0, 1),
    ('slider', 'rootHaloDepth', 1, 5),
    ('slider', 'rootDiffusionSpeed', 0.2, 4),
    ('slider', 'cameraSpeed', 0.1, 5),
    ('compare-shape', 'tetrahedron'), ('compare-shape', 'cube'),
    ('compare-shape', 'octahedron'), ('compare-shape', 'dodecahedron'),
    ('compare-shape', 'icosahedron'),
    ('compare-mode', 'overlay'), ('compare-mode', 'intersection'),
    ('compare-mode', 'difference'),
    ('preset', 'coxeter-rings'), ('preset', 'subset-diff'),
    ('preset', 'sdf-metal'), ('preset', 'platonic-bloom'),
    ('preset', '600-bridge'), ('preset', 'weyl-chamber'),
    ('preset', 'twin-600'), ('preset', 'aurora-borealis'),
    ('preset', 'deep-space'), ('preset', 'cosmic-dawn'),
    ('preset', 'mandala-meditation'), ('preset', 'plasma-storm'),
    ('preset', 'tron-grid'), ('preset', 'milky-meditation'),
]

# Maps to JS action calls — uses ACTUAL method names from main.js, not naive
# string-conversion of the action-id (which would e.g. mangle 'e8-twin-600' to
# 'toggleE8twin600' instead of 'toggleE8Twin600').
ACTION_SCRIPT = {
    'view':          lambda a: f"window.__app.switchView('{a[1]}')",
    'palette':       lambda a: f"window.__app.setPalette('{a[1]}')",
    'fx':            lambda a: f"window.__app.setFX('{a[1]}')",
    'bg':            lambda a: f"window.__app.setBgMode('{a[1]}')",
    'theme':         lambda a: f"window.__app.setTheme('{a[1]}')",
    'layout':        lambda a: f"window.__app.setLayout('{a[1]}')",
    'shape':         lambda a: f"window.__app.setShape('{a[1]}')",
    'stack':         lambda a: f"window.__app.setStackMode('{a[1]}')",
    'blend':         lambda a: f"window.__app.setBlendMode('{a[1]}')",
    'colorBy':       lambda a: f"window.__app.setColorBy('{a[1]}')",
    'sliderAuto':    lambda a: f"window.__app.toggleSliderAuto('{a[1]}')",
    'shift':         lambda a: f"window.__app.setShiftMode('{a[1]}')",
    'cam-mode':      lambda a: f"window.__app.setCameraMode('{a[1]}')",
    'cam-path':      lambda a: f"window.__app.setCameraPath('{a[1]}')",
    'toggle':        lambda a: f"window.__app.{TOGGLE_METHODS[a[1]]}()",
    'e8-mode':       lambda a: f"window.__app.setE8Mode('{a[1]}')",
    'action':        lambda a: f"window.__app.{ACTION_METHODS[a[1]]}()",
    'slider':        None,  # requires random + bounds — set up in fuzzer
    'compare-shape': lambda a: f"window.__app.setCompareShape('{a[1]}')",
    'compare-mode':  lambda a: f"window.__app.setCompareMode('{a[1]}')",
    'preset':        lambda a: f"window.__app.applyGalleryPreset('{a[1]}')",
}

# Explicit map from action-id → actual toggle method name
TOGGLE_METHODS = {
    'autoRotate':          'toggleAutoRotate',
    'autoZoom':            'toggleAutoZoom',
    'rootDiffusion':       'toggleRootDiffusion',
    'showPetrie':          'togglePetrie',
    'showRings':           'toggleRings',
    'showEdges':           'toggleEdges',
    'e8Twin600':           'toggleE8Twin600',
    'e8ProjectionAuto':    'toggleProjectionAuto',
    'weylOrbit':           'toggleWeylOrbit',
    'showWeylMirrors':     'toggleWeylMirrors',
    'h4TwinReveal':        'toggleH4TwinReveal',
    'bloomMandelbox':      'toggleBloomMandelbox',
    'bloomAuto':           'toggleBloomAuto',
    'paused':              'togglePause',
    'showInspector':       'toggleRootInspector',
    'showPerf':            'togglePerf',
    'adaptivePixelRatio':  'toggleAdaptivePixelRatio',
    'cartanHighlight':     'toggleCartanHighlight',
}

ACTION_METHODS = {
    'surprise':               'surprise',
    'resetCamera':             'resetCamera',
    'resetE8Angles':           'resetE8Angles',
    'resetPolyAngles':         'resetPolyAngles',
    'sharePage':               'sharePage',
    'shareSnapshot':           'shareSnapshot',
    'toggleTour':              'toggleTour',
    'togglePerf':              'togglePerf',
    'toggleCommandPalette':    'toggleCommandPalette',
}
